name: hello-world
on:
    pull_request:
        branches: [ "main" ]
        paths:
          - '**'
          - '!.github/**'
          - '!**/*.md'
        
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: check aws
        run: aws --version
